In [1]:
#Importing the libraries 
import numpy as np
import pandas as pd
import sklearn.metrics as mse
# Importing libraries to handle categorical data 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
# Importing libraries to split into train and test sets 
from sklearn.model_selection import train_test_split
#Importing libraries to handle feature scaling 
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("50_Startups.csv")
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
#checking for missing data if there is any and how many 
df.isnull().sum()

R&D Spend          0
Administration     1
Marketing Spend    1
State              0
Profit             0
dtype: int64

In [4]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   49 non-null     float64
 2   Marketing Spend  49 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [5]:
#since we got some missing values we need to handle them so we need to do following
# Replace missing values  with the mean (because data is numerical)
df['Administration'].fillna(df['Administration'].mean(), inplace = True)
df['Marketing Spend'].fillna(df['Marketing Spend'].mean(), inplace = True)

In [6]:
# so as we see now the dataset has zero missing value so we can proceed
df.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [7]:
#Splitting data into inputs as x and outputs as y
x = df.iloc[:, 0:4]
x.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [8]:
y = df.iloc[:, -1:].values
y

array([[192261.83],
       [191792.06],
       [191050.39],
       [182901.99],
       [166187.94],
       [156991.12],
       [156122.51],
       [155752.6 ],
       [152211.77],
       [149759.96],
       [146121.95],
       [144259.4 ],
       [141585.52],
       [134307.35],
       [132602.65],
       [129917.04],
       [126992.93],
       [125370.37],
       [124266.9 ],
       [122776.86],
       [118474.03],
       [111313.02],
       [110352.25],
       [108733.99],
       [108552.04],
       [107404.34],
       [105733.54],
       [105008.31],
       [103282.38],
       [101004.64],
       [ 99937.59],
       [ 97483.56],
       [ 97427.84],
       [ 96778.92],
       [ 96712.8 ],
       [ 96479.51],
       [ 90708.19],
       [ 89949.14],
       [ 81229.06],
       [ 81005.76],
       [ 78239.91],
       [ 77798.83],
       [ 71498.49],
       [ 69758.98],
       [ 65200.33],
       [ 64926.08],
       [ 49490.75],
       [ 42559.73],
       [ 35673.41],
       [ 14681.4 ]])

In [9]:
#Handling categorical data and convert them into binary
ct = ColumnTransformer([('one', OneHotEncoder(), [3])], remainder = 'passthrough')
x = ct.fit_transform(x)

In [10]:
df["State"].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [11]:
x

array([[0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.65349200e+05,
        1.36897800e+05, 4.71784100e+05],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.62597700e+05,
        1.51377590e+05, 4.43898530e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.53441510e+05,
        1.01145550e+05, 4.07934540e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.44372410e+05,
        1.18671850e+05, 3.83199620e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.42107340e+05,
        9.13917700e+04, 3.66168420e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.31876900e+05,
        9.98147100e+04, 3.62861360e+05],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.34615460e+05,
        1.47198870e+05, 2.12725267e+05],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.30298130e+05,
        1.45530060e+05, 3.23876680e+05],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.20542520e+05,
        1.48718950e+05, 

In [12]:
# Splitting data to train sets and test sets
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, random_state = 0)

In [13]:
print('Inputs shape ', x.shape)
print('Outputs shape ', y.shape)
print('x_train shape ', x_train.shape)
print('x_test shape ', x_test.shape)
print('y_train shape ', y_train.shape)
print('y_test shape', y_test.shape)

Inputs shape  (50, 6)
Outputs shape  (50, 1)
x_train shape  (40, 6)
x_test shape  (10, 6)
y_train shape  (40, 1)
y_test shape (10, 1)


In [14]:
#feature scaling 
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [15]:
# DL libraries
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [16]:
ob=Sequential()
ob.add(Dense(units=6,kernel_initializer= "random_uniform",activation= "relu"))# Input layer
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 1
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 2 
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 3 
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 4 
ob.add(Dense(units=12,kernel_initializer= "random_uniform",activation= "relu"))# Hidden layer 5
ob.add(Dense(units=1,kernel_initializer= "random_uniform",activation= "relu"))#  Output layer 
ob.compile(optimizer="rmsprop",loss="mean_squared_error")# Compiling model

In [17]:
ob.fit(x_train, y_train, epochs = 1000)# Training the model


Epoch 1/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615994880.0000
Epoch 2/1000
2/2 [==============================] - 0s 997us/step - loss: 13615993856.0000
Epoch 3/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615992832.0000
Epoch 4/1000
2/2 [==============================] - 0s 4ms/step - loss: 13615991808.0000
Epoch 5/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615990784.0000
Epoch 6/1000
2/2 [==============================] - 0s 997us/step - loss: 13615988736.0000
Epoch 7/1000
2/2 [==============================] - 0s 3ms/step - loss: 13615988736.0000
Epoch 8/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615986688.0000
Epoch 9/1000
2/2 [==============================] - 0s 2ms/step - loss: 13615986688.0000
Epoch 10/1000
2/2 [==============================] - 0s 3ms/step - loss: 13615985664.0000
Epoch 11/1000
2/2 [==============================] - 0s 4ms/step - loss: 13615983616.0000
Epoch 12/1000
2

Epoch 92/1000
2/2 [==============================] - 0s 3ms/step - loss: 13608102912.0000
Epoch 93/1000
2/2 [==============================] - 0s 2ms/step - loss: 13607651328.0000
Epoch 94/1000
2/2 [==============================] - 0s 1ms/step - loss: 13607119872.0000
Epoch 95/1000
2/2 [==============================] - 0s 1ms/step - loss: 13606590464.0000
Epoch 96/1000
2/2 [==============================] - 0s 1ms/step - loss: 13606025216.0000
Epoch 97/1000
2/2 [==============================] - 0s 1ms/step - loss: 13605464064.0000
Epoch 98/1000
2/2 [==============================] - 0s 1ms/step - loss: 13604872192.0000
Epoch 99/1000
2/2 [==============================] - 0s 2ms/step - loss: 13604265984.0000
Epoch 100/1000
2/2 [==============================] - 0s 8ms/step - loss: 13603672064.0000
Epoch 101/1000
2/2 [==============================] - 0s 2ms/step - loss: 13603112960.0000
Epoch 102/1000
2/2 [==============================] - 0s 2ms/step - loss: 13602428928.0000
Epoch 1

2/2 [==============================] - 0s 1ms/step - loss: 13284176896.0000
Epoch 183/1000
2/2 [==============================] - 0s 1ms/step - loss: 13275080704.0000
Epoch 184/1000
2/2 [==============================] - 0s 1ms/step - loss: 13264766976.0000
Epoch 185/1000
2/2 [==============================] - 0s 3ms/step - loss: 13252582400.0000
Epoch 186/1000
2/2 [==============================] - 0s 3ms/step - loss: 13241112576.0000
Epoch 187/1000
2/2 [==============================] - 0s 997us/step - loss: 13229735936.0000
Epoch 188/1000
2/2 [==============================] - 0s 2ms/step - loss: 13215424512.0000
Epoch 189/1000
2/2 [==============================] - 0s 2ms/step - loss: 13203366912.0000
Epoch 190/1000
2/2 [==============================] - 0s 1ms/step - loss: 13193505792.0000
Epoch 191/1000
2/2 [==============================] - 0s 997us/step - loss: 13181770752.0000
Epoch 192/1000
2/2 [==============================] - 0s 2ms/step - loss: 13167929344.0000
Epoch 193/

Epoch 272/1000
2/2 [==============================] - 0s 8ms/step - loss: 10482300928.0000
Epoch 273/1000
2/2 [==============================] - 0s 7ms/step - loss: 10426269696.0000
Epoch 274/1000
2/2 [==============================] - 0s 3ms/step - loss: 10363949056.0000
Epoch 275/1000
2/2 [==============================] - 0s 5ms/step - loss: 10301039616.0000
Epoch 276/1000
2/2 [==============================] - 0s 5ms/step - loss: 10228152320.0000
Epoch 277/1000
2/2 [==============================] - 0s 5ms/step - loss: 10151598080.0000
Epoch 278/1000
2/2 [==============================] - 0s 3ms/step - loss: 10076131328.0000
Epoch 279/1000
2/2 [==============================] - 0s 996us/step - loss: 10005454848.0000
Epoch 280/1000
2/2 [==============================] - 0s 6ms/step - loss: 9938526208.0000
Epoch 281/1000
2/2 [==============================] - 0s 2ms/step - loss: 9871851520.0000
Epoch 282/1000
2/2 [==============================] - 0s 997us/step - loss: 9802235904.000

2/2 [==============================] - 0s 2ms/step - loss: 2543912192.0000
Epoch 362/1000
2/2 [==============================] - 0s 2ms/step - loss: 2471177728.0000
Epoch 363/1000
2/2 [==============================] - 0s 2ms/step - loss: 2405934592.0000
Epoch 364/1000
2/2 [==============================] - 0s 5ms/step - loss: 2342495744.0000
Epoch 365/1000
2/2 [==============================] - 0s 6ms/step - loss: 2280065536.0000
Epoch 366/1000
2/2 [==============================] - 0s 4ms/step - loss: 2218471936.0000
Epoch 367/1000
2/2 [==============================] - 0s 6ms/step - loss: 2159477248.0000
Epoch 368/1000
2/2 [==============================] - 0s 4ms/step - loss: 2106386176.0000
Epoch 369/1000
2/2 [==============================] - 0s 2ms/step - loss: 2053372928.0000
Epoch 370/1000
2/2 [==============================] - 0s 7ms/step - loss: 2010631552.0000
Epoch 371/1000
2/2 [==============================] - 0s 4ms/step - loss: 1976180096.0000
Epoch 372/1000
2/2 [=====

2/2 [==============================] - 0s 12ms/step - loss: 788154496.0000
Epoch 453/1000
2/2 [==============================] - 0s 1ms/step - loss: 778021248.0000
Epoch 454/1000
2/2 [==============================] - 0s 5ms/step - loss: 769805440.0000
Epoch 455/1000
2/2 [==============================] - 0s 2ms/step - loss: 762590720.0000
Epoch 456/1000
2/2 [==============================] - 0s 1ms/step - loss: 756404608.0000
Epoch 457/1000
2/2 [==============================] - 0s 1ms/step - loss: 749114368.0000
Epoch 458/1000
2/2 [==============================] - 0s 7ms/step - loss: 740490496.0000
Epoch 459/1000
2/2 [==============================] - 0s 4ms/step - loss: 731357952.0000
Epoch 460/1000
2/2 [==============================] - 0s 2ms/step - loss: 724228608.0000
Epoch 461/1000
2/2 [==============================] - 0s 7ms/step - loss: 714894848.0000
Epoch 462/1000
2/2 [==============================] - 0s 6ms/step - loss: 703418752.0000
Epoch 463/1000
2/2 [===============

2/2 [==============================] - 0s 2ms/step - loss: 298898176.0000
Epoch 543/1000
2/2 [==============================] - 0s 997us/step - loss: 294810912.0000
Epoch 544/1000
2/2 [==============================] - 0s 2ms/step - loss: 291731776.0000
Epoch 545/1000
2/2 [==============================] - 0s 1ms/step - loss: 289066656.0000
Epoch 546/1000
2/2 [==============================] - 0s 997us/step - loss: 288025152.0000
Epoch 547/1000
2/2 [==============================] - 0s 3ms/step - loss: 284881856.0000
Epoch 548/1000
2/2 [==============================] - 0s 2ms/step - loss: 282103104.0000
Epoch 549/1000
2/2 [==============================] - 0s 1ms/step - loss: 277129504.0000
Epoch 550/1000
2/2 [==============================] - 0s 2ms/step - loss: 274091360.0000
Epoch 551/1000
2/2 [==============================] - 0s 997us/step - loss: 272559776.0000
Epoch 552/1000
2/2 [==============================] - 0s 2ms/step - loss: 269971680.0000
Epoch 553/1000
2/2 [==========

2/2 [==============================] - 0s 6ms/step - loss: 161203536.0000
Epoch 633/1000
2/2 [==============================] - 0s 3ms/step - loss: 159972000.0000
Epoch 634/1000
2/2 [==============================] - 0s 5ms/step - loss: 159413472.0000
Epoch 635/1000
2/2 [==============================] - 0s 1ms/step - loss: 158757376.0000
Epoch 636/1000
2/2 [==============================] - 0s 2ms/step - loss: 159610592.0000
Epoch 637/1000
2/2 [==============================] - 0s 997us/step - loss: 158663120.0000
Epoch 638/1000
2/2 [==============================] - ETA: 0s - loss: 176374240.000 - 0s 3ms/step - loss: 158247440.0000
Epoch 639/1000
2/2 [==============================] - 0s 4ms/step - loss: 158122400.0000
Epoch 640/1000
2/2 [==============================] - 0s 5ms/step - loss: 156914592.0000
Epoch 641/1000
2/2 [==============================] - 0s 5ms/step - loss: 156360832.0000
Epoch 642/1000
2/2 [==============================] - 0s 2ms/step - loss: 156125696.0000
Ep

2/2 [==============================] - 0s 998us/step - loss: 120050864.0000
Epoch 724/1000
2/2 [==============================] - 0s 1ms/step - loss: 120475800.0000
Epoch 725/1000
2/2 [==============================] - 0s 1000us/step - loss: 119955696.0000
Epoch 726/1000
2/2 [==============================] - 0s 1ms/step - loss: 118940456.0000
Epoch 727/1000
2/2 [==============================] - 0s 998us/step - loss: 117030464.0000
Epoch 728/1000
2/2 [==============================] - 0s 2ms/step - loss: 116617816.0000
Epoch 729/1000
2/2 [==============================] - 0s 998us/step - loss: 117401048.0000
Epoch 730/1000
2/2 [==============================] - 0s 998us/step - loss: 117263024.0000
Epoch 731/1000
2/2 [==============================] - 0s 2ms/step - loss: 116022808.0000
Epoch 732/1000
2/2 [==============================] - 0s 997us/step - loss: 115667992.0000
Epoch 733/1000
2/2 [==============================] - 0s 1ms/step - loss: 115076304.0000
Epoch 734/1000
2/2 [===

2/2 [==============================] - 0s 1ms/step - loss: 95993328.0000
Epoch 815/1000
2/2 [==============================] - 0s 2ms/step - loss: 95818008.0000
Epoch 816/1000
2/2 [==============================] - 0s 1ms/step - loss: 96795568.0000
Epoch 817/1000
2/2 [==============================] - 0s 4ms/step - loss: 96983608.0000
Epoch 818/1000
2/2 [==============================] - 0s 2ms/step - loss: 95445648.0000
Epoch 819/1000
2/2 [==============================] - 0s 2ms/step - loss: 95536784.0000
Epoch 820/1000
2/2 [==============================] - 0s 2ms/step - loss: 95320488.0000
Epoch 821/1000
2/2 [==============================] - 0s 998us/step - loss: 95615784.0000
Epoch 822/1000
2/2 [==============================] - 0s 2ms/step - loss: 95940688.0000
Epoch 823/1000
2/2 [==============================] - 0s 1ms/step - loss: 94658400.0000
Epoch 824/1000
2/2 [==============================] - 0s 3ms/step - loss: 94071088.0000
Epoch 825/1000
2/2 [=========================

2/2 [==============================] - 0s 998us/step - loss: 82297048.0000
Epoch 907/1000
2/2 [==============================] - 0s 997us/step - loss: 82253040.0000
Epoch 908/1000
2/2 [==============================] - 0s 998us/step - loss: 82829104.0000
Epoch 909/1000
2/2 [==============================] - 0s 1ms/step - loss: 84118192.0000
Epoch 910/1000
2/2 [==============================] - 0s 1ms/step - loss: 83061384.0000
Epoch 911/1000
2/2 [==============================] - 0s 2ms/step - loss: 81812808.0000
Epoch 912/1000
2/2 [==============================] - 0s 2ms/step - loss: 81604208.0000
Epoch 913/1000
2/2 [==============================] - 0s 2ms/step - loss: 81704464.0000
Epoch 914/1000
2/2 [==============================] - 0s 2ms/step - loss: 83173200.0000
Epoch 915/1000
2/2 [==============================] - 0s 1ms/step - loss: 84656976.0000
Epoch 916/1000
2/2 [==============================] - 0s 3ms/step - loss: 85371800.0000
Epoch 917/1000
2/2 [=====================

2/2 [==============================] - 0s 4ms/step - loss: 73791552.0000
Epoch 999/1000
2/2 [==============================] - 0s 4ms/step - loss: 73819688.0000
Epoch 1000/1000
2/2 [==============================] - 0s 1ms/step - loss: 72749840.0000


In [18]:
ypred = ob.predict(x_test)
ypred

array([[ 72669.64 ],
       [158084.53 ],
       [106841.84 ],
       [ 46979.52 ],
       [174068.7  ],
       [120548.266],
       [ 76665.625],
       [105431.516],
       [ 85950.72 ],
       [158339.9  ]], dtype=float32)

In [19]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])